-- Create AuditAction enum
CREATE TYPE "AuditAction" AS ENUM (
  'USER_CREATED',
  'USER_UPDATED', 
  'USER_STATUS_UPDATED',
  'USER_DELETED',
  'LOGIN_SUCCESS',
  'LOGIN_FAILURE',
  'LOGOUT',
  'PASSWORD_CHANGE_SUCCESS',
  'PASSWORD_CHANGE_FAILURE',
  'PASSWORD_RESET_REQUESTED',
  'PASSWORD_RESET_SUCCESS',
  'PATIENT_CREATED',
  'PATIENT_UPDATED',
  'PATIENT_DELETED',
  'PATIENT_VIEWED',
  'VISIT_CREATED',
  'VISIT_UPDATED',
  'VISIT_COMPLETED',
  'VITALS_RECORDED',
  'CLINICAL_NOTE_ADDED',
  'DIAGNOSIS_ADDED',
  'PRESCRIPTION_ISSUED',
  'LAB_ORDER_CREATED'
);

-- Alter audit_logs table to use the new enum type
ALTER TABLE "audit_logs" ALTER COLUMN "action" TYPE "AuditAction" USING "action"::text::"AuditAction";